# Generated by Django 4.2 on 2023-05-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="has_voted",
            field=models.BooleanField(default=False),
        ),
    ]
