# Generated by Django 4.2.1 on 2023-05-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0010_togglevoting"),
        ("users", "0002_user_has_voted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="has_voted",
        ),
        migrations.AddField(
            model_name="user",
            name="voted_positions",
            field=models.ManyToManyField(to="polls.position"),
        ),
    ]
