# Generated by Django 4.2 on 2023-05-06 17:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0002_position_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vote",
            name="poll",
        ),
    ]
