# Generated by Django 4.2 on 2023-05-06 18:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("polls", "0003_remove_vote_poll"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vote",
            name="choice",
        ),
        migrations.AddField(
            model_name="poll",
            name="user",
            field=models.ManyToManyField(
                blank=True, null=True, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="poll",
            name="vote",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vote",
            name="candidate",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="votes", to="polls.candidate"
            ),
        ),
        migrations.DeleteModel(
            name="Choice",
        ),
    ]
