# Generated by Django 4.2 on 2023-05-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0004_remove_vote_choice_poll_user_poll_vote_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="vote",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
