# Generated by Django 4.2.1 on 2023-05-06 18:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("polls", "0006_candidate_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="user",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="vote",
            name="candidate",
            field=models.ManyToManyField(related_name="votes", to="polls.candidate"),
        ),
    ]
