# Generated by Django 4.2.1 on 2023-05-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0009_alter_poll_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="ToggleVoting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("voting", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
