# Generated by Django 4.2.1 on 2023-05-20 17:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0010_togglevoting"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Vote",
        ),
    ]
